#ifndef SPRITE_DATA_H
#define SPRITE_DATA_H

extern const uint8_t bitmap_commandant_facing_top_left_1[];
extern const uint8_t bitmap_commandant_facing_top_left_2[];
extern const uint8_t bitmap_commandant_facing_top_left_3[];
extern const uint8_t bitmap_commandant_facing_top_left_4[];
extern const uint8_t bitmap_commandant_facing_bottom_right_1[];
extern const uint8_t bitmap_commandant_facing_bottom_right_2[];
extern const uint8_t bitmap_commandant_facing_bottom_right_3[];
extern const uint8_t bitmap_commandant_facing_bottom_right_4[];
extern const uint8_t bitmap_prisoner_facing_top_left_1[];
extern const uint8_t bitmap_prisoner_facing_top_left_2[];
extern const uint8_t bitmap_prisoner_facing_top_left_3[];
extern const uint8_t bitmap_prisoner_facing_top_left_4[];
extern const uint8_t bitmap_prisoner_facing_bottom_right_1[];
extern const uint8_t bitmap_prisoner_facing_bottom_right_2[];
extern const uint8_t bitmap_prisoner_facing_bottom_right_3[];
extern const uint8_t bitmap_prisoner_facing_bottom_right_4[];
extern const uint8_t bitmap_crawl_facing_bottom_left_1[];
extern const uint8_t bitmap_crawl_facing_bottom_left_2[];
extern const uint8_t bitmap_crawl_facing_top_left_1[];
extern const uint8_t bitmap_crawl_facing_top_left_2[];
extern const uint8_t mask_crawl_facing_top_left[];
extern const uint8_t mask_various_facing_top_left_1[];
extern const uint8_t mask_various_facing_top_left_2[];
extern const uint8_t mask_various_facing_top_left_3[];
extern const uint8_t mask_various_facing_top_left_4[];
extern const uint8_t mask_various_facing_bottom_right_1[];
extern const uint8_t mask_various_facing_bottom_right_2[];
extern const uint8_t mask_various_facing_bottom_right_3[];
extern const uint8_t mask_various_facing_bottom_right_4[];
extern const uint8_t mask_crawl_facing_bottom_left[];
extern const uint8_t bitmap_guard_facing_top_left_1[];
extern const uint8_t bitmap_guard_facing_top_left_2[];
extern const uint8_t bitmap_guard_facing_top_left_3[];
extern const uint8_t bitmap_guard_facing_top_left_4[];
extern const uint8_t bitmap_guard_facing_bottom_right_1[];
extern const uint8_t bitmap_guard_facing_bottom_right_2[];
extern const uint8_t bitmap_guard_facing_bottom_right_3[];
extern const uint8_t bitmap_guard_facing_bottom_right_4[];
extern const uint8_t bitmap_dog_facing_top_left_1[];
extern const uint8_t bitmap_dog_facing_top_left_2[];
extern const uint8_t bitmap_dog_facing_top_left_3[];
extern const uint8_t bitmap_dog_facing_top_left_4[];
extern const uint8_t mask_dog_facing_top_left[];
extern const uint8_t bitmap_dog_facing_bottom_right_1[];
extern const uint8_t bitmap_dog_facing_bottom_right_2[];
extern const uint8_t bitmap_dog_facing_bottom_right_3[];
extern const uint8_t bitmap_dog_facing_bottom_right_4[];
extern const uint8_t mask_dog_facing_bottom_right[];
extern const uint8_t flag_up[];
extern const uint8_t flag_down[];
extern const uint8_t bitmap_crate[];
extern const uint8_t mask_crate[];
extern const uint8_t bitmap_stove[];
extern const uint8_t mask_stove[];

#endif /* SPRITE_DATA_H */

